import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      // Auto-update the SW in the background; injectRegister:'auto' lets the
      // plugin inject a tiny registration snippet into the built HTML so we do
      // NOT import `virtual:pwa-register` in app source (keeps vitest/jsdom
      // untouched — vitest.config.ts doesn't load this plugin anyway).
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      // Icons live in /public/icons and are authored + generated by
      // scripts/gen-icons.mjs (npm run icons:build).
      includeAssets: ['icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-512.png'],
      manifest: {
        name: 'Mockopoly',
        short_name: 'Mockopoly',
        description: 'Real-time multiplayer Monopoly in 3D.',
        theme_color: '#08080f',
        background_color: '#08080f',
        display: 'standalone',
        orientation: 'any',
        start_url: '/',
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // Precache the app shell. The big async GameScene chunk matches *.js so
        // it is precached (downloaded in the background AFTER first paint) — it
        // is NOT modulepreloaded into first paint, so this does not regress the
        // initial-load bundle.
        globPatterns: ['**/*.{js,css,html,woff2,ttf}'],
        // The GameScene chunk + precache manifest can exceed the default 2 MiB
        // cap; raise it so precaching succeeds. (This is a background cache
        // budget, not a first-paint download.)
        maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
        runtimeCaching: [
          {
            // 3D token / building / city models: cache-first so a game that has
            // been played once works fully offline.
            urlPattern: ({ url }) => /\/models\/.*\.glb$/.test(url.pathname),
            handler: 'CacheFirst',
            options: {
              cacheName: 'mockopoly-models',
              expiration: {
                maxEntries: 32,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  server: { port: 5174 },
  build: {
    chunkSizeWarningLimit: 1200,
  },
});
